author = "jimsynz"
description = "Elixir for Lapce: powered by elixir-ls"
display-name = "Elixir"
name = "lapce-elixir"
repository = "jimsynz/lapce-elixir"
version = "0.1.0"
wasm = "lapce-elixir.wasm"

[configuration]
language_id = "elixir"
